version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/*.war ROOT.war

artifacts:
  files:
    'ROOT.war'

cache:
  paths:
    - '/root/.m2/**/*'
