version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - mkdir artifact
      - unzip target/VehicleService-0.0.1-RELEASE.war -d ./artifact/

artifacts:
  files:
    - artifact/**
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
