version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo Build started on `date`
      - mvn clean pacakge
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir artifact
      - unzip target/VehicleService-0.0.1-RELEASE.war -d artifact/
artifacts:
  files:
    - artifact/**/*
    - name: artifact

cache:
  paths:
    - '/root/.m2/**/*'
